version: "3.9"
services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: [mongo_data:/data/db]
  mongo-express:
    image: mongo-express:1
    ports: ["8081:8081"]
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
volumes:
  mongo_data:
